# Generated by Django 4.0 on 2022-01-04 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('default', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(choices=[('High School/Secondary School', 'High School/Secondary School'), ('University (Undergrad)', 'University (Undergrad)'), ("University (Master's/Doctoral)", "University (Master's/Doctoral)")], max_length=60)),
                ('major', models.CharField(default='other', max_length=60)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hacker', to='default.customuser')),
            ],
            options={
                'verbose_name': 'Hacker',
            },
        ),
    ]
