# Generated by Django 3.2.5 on 2021-07-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hacker',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hacker',
            name='food_preference',
            field=models.CharField(choices=[('None', 'None'), ('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan'), ('Gluten-Free', 'Gluten-Free')], default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='hacker',
            name='shirt_size',
            field=models.CharField(choices=[('Unisex (XS)', 'Unisex (XS)'), ('Unisex (S)', 'Unisex (S)'), ('Unisex (M)', 'Unisex (M)'), ('Unisex (L)', 'Unisex (L)'), ('Unisex (2XL)', 'Unisex (2XL)'), ('Unisex (3XL)', 'Unisex (3XL)')], default='Unisex (M)', max_length=20),
        ),
    ]
