# Generated by Django 4.0.3 on 2022-05-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0002_alter_customuser_shirt_size'),
        ('hacker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackerinfo',
            name='rsvp_list',
            field=models.ManyToManyField(related_name='rsvp', to='default.event'),
        ),
    ]
