# Generated by Django 3.2.5 on 2021-08-11 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hacker', '0002_auto_20210730_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hacker',
            name='checked_in',
        ),
    ]
