# Generated by Django 4.0 on 2022-01-05 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacker', '0002_alter_hackerinfo_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackerinfo',
            name='education',
            field=models.CharField(choices=[('High School/Secondary School', 'High School/Secondary School'), ('University (Undergrad)', 'University (Undergrad)'), ("University (Master's/Doctoral)", "University (Master's/Doctoral)")], default='other', max_length=60),
        ),
        migrations.AlterField(
            model_name='hackerinfo',
            name='major',
            field=models.CharField(choices=[('Accounting', 'Accounting'), ('Biology', 'Biology'), ('Biomedical Engineering', 'Biomedical Engineering'), ('Business Administration', 'Business Administration'), ('Chemistry', 'Chemistry'), ('Civil Engineering', 'Civil Engineering'), ('Communications', 'Communications'), ('Computer Engineering', 'Computer Engineering'), ('Computer Science', 'Computer Science'), ('Construction Management', 'Construction Management'), ('Cybersecurity', 'Cybersecurity'), ('Economics', 'Economics'), ('Education', 'Education'), ('Electronics Engineering', 'Electronics Engineering'), ('English', 'English'), ('Finance', 'Finance'), ('Game Design', 'Game Design'), ('Health Informatics', 'Health Informatics'), ('Industrial Engineering', 'Industrial Engineering'), ('Interactive Multimedia', 'Interactive Multimedia'), ('Information Technology', 'Information Technology'), ('Liberal Arts', 'Liberal Arts'), ('Management', 'Management'), ('Management Information Systems', 'Management Information Systems'), ('Marketing', 'Marketing'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Nuclear Engineering', 'Nuclear Engineering'), ('Nursing', 'Nursing'), ('Petroleum Engineering', 'Petroleum Engineering'), ('Physics', 'Physics'), ('Political Science', 'Political Science'), ('Public Administration', 'Public Administration'), ('Software Engineering', 'Software Engineering')], default='other', max_length=60),
        ),
    ]
