# Generated by Django 4.0.1 on 2022-02-13 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(max_length=100)),
                ('permission_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Feature Permission',
            },
        ),
        migrations.CreateModel(
            name='OrganizerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organizer',
            },
        ),
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiting_list_status', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
            ],
            options={
                'verbose_name': 'Waiting List Setting',
            },
        ),
        migrations.CreateModel(
            name='OrganizerPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to='organizer.organizerinfo')),
                ('permission', models.ManyToManyField(related_name='organizer_permission', to='organizer.FeaturePermission')),
            ],
            options={
                'verbose_name': 'Organizer Permissions',
            },
        ),
    ]
