# Generated by Django 4.0 on 2022-01-04 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('default', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingListSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Waiting List Supervisor',
            },
        ),
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiting_list_status', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
            ],
            options={
                'verbose_name': 'Waiting List Setting',
            },
        ),
        migrations.CreateModel(
            name='OrganizerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to='default.customuser')),
            ],
            options={
                'verbose_name': 'Organizer',
            },
        ),
    ]
