# Generated by Django 4.0.1 on 2022-02-13 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WaitingListSupervisor',
        ),
    ]
