# Generated by Django 4.0 on 2022-01-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingListControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiting_list_status', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
            ],
            options={
                'verbose_name': 'Waiting List Setting',
            },
        ),
        migrations.CreateModel(
            name='WaitingListSupervisors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Waiting List Supervisor',
            },
        ),
    ]
