# Generated by Django 4.0.1 on 2022-02-13 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_delete_waitinglistsupervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(max_length=100)),
                ('permission_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Feature Permission',
            },
        ),
        migrations.CreateModel(
            name='OrganizerPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to='organizer.organizerinfo')),
                ('permission', models.ManyToManyField(to='organizer.FeaturePermission')),
            ],
            options={
                'verbose_name': 'Organizer Permissions',
            },
        ),
    ]
