# Generated by Django 4.0.1 on 2022-02-13 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_featurepermission_organizerpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizerpermission',
            name='permission',
            field=models.ManyToManyField(related_name='organizer_permission', to='organizer.FeaturePermission'),
        ),
    ]
