# Generated by Django 4.0.2 on 2022-03-16 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'doc'])]),
        ),
    ]
