# Generated by Django 4.0.3 on 2022-05-16 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='shirt_size',
            field=models.CharField(choices=[('Unisex (XS)', 'Unisex (XS)'), ('Unisex (S)', 'Unisex (S)'), ('Unisex (M)', 'Unisex (M)'), ('Unisex (L)', 'Unisex (L)'), ('Unisex (XL)', 'Unisex (XL)'), ('Unisex (2XL)', 'Unisex (2XL)'), ('Unisex (3XL)', 'Unisex (3XL)')], default='Unisex (M)', max_length=20),
        ),
    ]
