# Generated by Django 3.2.5 on 2021-08-02 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
            ],
        ),
    ]
