# Generated by Django 4.0.3 on 2023-03-01 00:21

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0002_alter_customuser_shirt_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=phone_field.models.PhoneField(default=6091234567, help_text='Contact phone number', max_length=31),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='level_of_study',
            field=models.CharField(choices=[('Less than Secondary / High School', 'Less than Secondary / High School'), ('Secondary / High School', 'Secondary / High School'), ('Undergraduate University (2 year - community college or similar)', 'Undergraduate University (2 year - community college or similar)'), ('Undergraduate University (3+ year)', 'Undergraduate University (3+ year)'), ('Graduate University (Masters, Professional, Doctoral, etc)', 'Graduate University (Masters, Professional, Doctoral, etc)'), ('Code School / Bootcamp', 'Code School / Bootcamp'), ('Other Vocational / Trade Program or Apprenticeship', 'Other Vocational / Trade Program or Apprenticeship'), ('Post Doctorate', 'Post Doctorate'), ('Other', 'Other'), ("I'm not currently a student", "I'm not currently a student"), ('Prefer not to answer', 'Prefer not to answer')], default='University (Undergrad)', max_length=100),
        ),
    ]
