# Generated by Django 4.0.3 on 2023-03-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0003_customuser_phone_alter_customuser_level_of_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=31),
        ),
    ]
