# Generated by Django 4.0.3 on 2023-11-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0004_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitinglist',
            name='email',
            field=models.EmailField(max_length=60, verbose_name='email'),
        ),
    ]
