# Generated by Django 4.0.3 on 2024-07-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0004_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
