# Generated by Django 4.0.3 on 2024-07-28 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0005_customuser_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='birth_date',
            new_name='dob',
        ),
    ]
